### ISSUE TITLE
THE VOICES

### ISSUE THREAD

**Issue by rangerdanger8805** [Astrum-Project/AstralXUtils#1]
it has been stopped :trollface:  🚎 

⣀⣠⣤⣤⣤⣤⢤⣤⣄⣀⣀⣀⣀⡀⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠉⠹⣾⣿⣛⣿⣿⣞⣿⣛⣺⣻⢾⣾⣿⣿⣿⣶⣶⣶⣄⡀⠄⠄⠄
⠄⠄⠠⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣆⠄⠄
⠄⠄⠘⠛⠛⠛⠛⠋⠿⣷⣿⣿⡿⣿⢿⠟⠟⠟⠻⠻⣿⣿⣿⣿⡀⠄
⠄⢀⠄⠄⠄⠄⠄⠄⠄⠄⢛⣿⣁⠄⠄⠒⠂⠄⠄⣀⣰⣿⣿⣿⣿⡀
⠄⠉⠛⠺⢶⣷⡶⠃⠄⠄⠨⣿⣿⡇⠄⡺⣾⣾⣾⣿⣿⣿⣿⣽⣿⣿
⠄⠄⠄⠄⠄⠛⠁⠄⠄⠄⢀⣿⣿⣧⡀⠄⠹⣿⣿⣿⣿⣿⡿⣿⣻⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠛⠟⠇⢀⢰⣿⣿⣿⣏⠉⢿⣽⢿⡏
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠠⠤⣤⣴⣾⣿⣿⣾⣿⣿⣦⠄⢹⡿⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠒⣳⣶⣤⣤⣄⣀⣀⡈⣀⢁⢁⢁⣈⣄⢐⠃⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣛⣻⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⣬⣽⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⢘⣿⣿⣻⣛⣿⡿⣟⣻⣿⣿⣿⣿⡟⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠛⢛⢿⣿⣿⣿⣿⣿⣿⣷⡿⠁⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠉⠉⠉⠈⠄⠄⠄⠄⠄⠄

**Comment by Mezque** [comment]
Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell themTell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_  to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell theTell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ m to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them toTell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_  shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them toTell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_  shut up** _Tell them to shut up tell them to shut upTell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_  tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_ Tell them to shut up tell them to shut up tell them to shut up **Tell them to shut up tell them to shut up tell them to shut up** **Tell them to shut up tell them to shut up tell them to shut up** _Tell them to shut up tell them to shut up tell them to shut up_

**Comment by Mezque** [comment]
why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?****why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?**why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this iswhy **did** you not _solve_ this issuisse?? ?why **did** you not _solve_ this issuisse?? ?suisse?? ?**

https://user-images.githubusercontent.com/31026406/149451604-f1053c87-d2ae-4b07-8650-024787709979.mp4

**

**Comment by Mezque** [comment]
that **will be you** if you dont solve the ### issue.
